# ==================================================
# Smart NGO Platform - Core Spring Dispatcher Config
# ==================================================

spring.application.name=smart-ngo-platform

# Server Port (assigned by Cloud Platform or default 8080)
server.port=${PORT:8080}

# Spring Active Profile (dev | test | prod)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Thymeleaf Cache Config
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
